USE [master]
GO

/****** Object:  Database [a07_DTGiang_FCPMS]    Script Date: 8/29/2024 8:07:44 PM ******/
CREATE DATABASE [a07_DTGiang_FCPMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'a07_DTGiang_FCPMS', FILENAME = N'D:\storage-sql\a07_DTGiang_FCPMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'a07_DTGiang_FCPMS_log', FILENAME = N'D:\storage-sql\a07_DTGiang_FCPMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [a07_DTGiang_FCPMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET RECOVERY FULL 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET  MULTI_USER 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET QUERY_STORE = ON
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [a07_DTGiang_FCPMS] SET  READ_WRITE 
GO


